# Generated by Django 5.1.4 on 2024-12-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('bmr', models.FloatField(null=True)),
                ('body_mass_index', models.FloatField(null=True)),
                ('effectiv_weight', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('fats', models.FloatField(null=True)),
                ('carbohydrates', models.FloatField(null=True)),
            ],
        ),
    ]
